//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLib.CORE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationStrings_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationStrings_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreLib.CORE.Resources.ValidationStrings.ru", typeof(ValidationStrings_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество элементов в последовательности &apos;{0}&apos; должно быть не менее {1}.
        /// </summary>
        public static string CollectionMinLengthError {
            get {
                return ResourceManager.GetString("CollectionMinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поля &apos;{0}&apos; и &apos;{1}&apos; должны совпадать.
        /// </summary>
        public static string CompareError {
            get {
                return ResourceManager.GetString("CompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля &apos;{0}&apos; должно быть больше значения поля &apos;{1}&apos;.
        /// </summary>
        public static string CompareToGreaterThanError {
            get {
                return ResourceManager.GetString("CompareToGreaterThanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля &apos;{0}&apos; должно быть больше или равно значению поля &apos;{1}&apos;.
        /// </summary>
        public static string CompareToGreaterThanOrEqualError {
            get {
                return ResourceManager.GetString("CompareToGreaterThanOrEqualError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля &apos;{0}&apos; должно быть меньше значения поля &apos;{1}&apos;.
        /// </summary>
        public static string CompareToSmallerThanError {
            get {
                return ResourceManager.GetString("CompareToSmallerThanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля &apos;{0}&apos; должно быть меньше или равно значению поля &apos;{1}&apos;.
        /// </summary>
        public static string CompareToSmallerThanOrEqualError {
            get {
                return ResourceManager.GetString("CompareToSmallerThanOrEqualError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последовательность &apos;{0}&apos; содержит элементы со следующими ошибками.
        /// </summary>
        public static string ComplexObjectCollectionValidationError {
            get {
                return ResourceManager.GetString("ComplexObjectCollectionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не может быть пустым.
        /// </summary>
        public static string ComplexObjectCollectionValidationError_ContainsNull {
            get {
                return ResourceManager.GetString("ComplexObjectCollectionValidationError_ContainsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент {0}: .
        /// </summary>
        public static string ComplexObjectCollectionValidationError_Index {
            get {
                return ResourceManager.GetString("ComplexObjectCollectionValidationError_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; имеет следующие ошибки.
        /// </summary>
        public static string ComplexObjectValidationError {
            get {
                return ResourceManager.GetString("ComplexObjectValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата в поле &apos;{0}&apos; должна лежать в диапазоне {1} - {2}.
        /// </summary>
        public static string DateTimeError {
            get {
                return ResourceManager.GetString("DateTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; должно иметь значение не менее {1} и не более {2}.
        /// </summary>
        public static string DigitRangeValuesError {
            get {
                return ResourceManager.GetString("DigitRangeValuesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект с таким названием уже существует.
        /// </summary>
        public static string DuplicateNameError {
            get {
                return ResourceManager.GetString("DuplicateNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один или несколько файлов не найдены.
        /// </summary>
        public static string FileNotFoundError {
            get {
                return ResourceManager.GetString("FileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время обработки файла произошла ошибка в строке: {0}.
        /// </summary>
        public static string FileParseByLineError {
            get {
                return ResourceManager.GetString("FileParseByLineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail введен некорректно.
        /// </summary>
        public static string InvalidEmailAddressFormatError {
            get {
                return ResourceManager.GetString("InvalidEmailAddressFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один или несколько файлов имеют некорректный путь сохранения.
        /// </summary>
        public static string InvalidFilePathError {
            get {
                return ResourceManager.GetString("InvalidFilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона введен некорректно.
        /// </summary>
        public static string InvalidPhoneFormatError {
            get {
                return ResourceManager.GetString("InvalidPhoneFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор объекта не найден.
        /// </summary>
        public static string NoIdError {
            get {
                return ResourceManager.GetString("NoIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не найден.
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; должно быть заполнено.
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так:(.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; имеет неверный формат.
        /// </summary>
        public static string StringFormatError {
            get {
                return ResourceManager.GetString("StringFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; должно содержать не более {1} символов.
        /// </summary>
        public static string StringMaxLengthError {
            get {
                return ResourceManager.GetString("StringMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; должно содержать не менее {1} символов.
        /// </summary>
        public static string StringMinLengthError {
            get {
                return ResourceManager.GetString("StringMinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; должно содержать не менее {1} и не более {2} символов.
        /// </summary>
        public static string StringRangeLengthError {
            get {
                return ResourceManager.GetString("StringRangeLengthError", resourceCulture);
            }
        }
    }
}
